
name: Test Package
on:
  push: # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: pylint
        run: |
          python -m pylint requirement_walker
      - name: pytest
        run: |
          python -m pytest --cov-report term-missing --cov=requirement_walker --cov-fail-under=80
      # - name: Build and publish
      #   env:
      #     TWINE_USERNAME: __token__
      #     TWINE_PASSWORD: ${{ secrets.PYPI_TEST_TOKEN }}
      #   run: |
      #     python setup.py sdist bdist_wheel
      #     twine upload dist/*

---
name: Deploy to PyPi
on:
  release:
    types: [created]
  workflow_run:
    workflows:
      - Test Package
    branches: [master]
    types: completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish
        env:
          TWINE_USERNAME: __toke__
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*