# objects:
# https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions
# syntax:
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: PyPi Test & Deploy Workflow
on:
  push:
jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
  
      - name: Set up Python
        id: setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
    
      - name: Install Dependencies
        id: install
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
  
      - name: pylint
        id: pylint
        run: |
          python -m pylint requirement_walker
  
      - name: pytest
        id: pytest
        run: |
          python -m pytest --cov-report term-missing --cov=requirement_walker --cov-fail-under=80
