name: Test Package
on:
  push: # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
  release:
    types: # This configuration does not affect the page_build event above
      - created
jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: pylint
        run: |
          python -m pylint requirement_walker
      - name: pytest
        run: |
          python -m pytest --cov-report term-missing --cov=requirement_walker --cov-fail-under=80
